### PR TITLE
initialize go module file

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
Half of #143.

**Comment by lavalamp** [comment]
Ran `go mod tidy` & updated.

**Comment by liggitt** [comment]
should this bump Travis.yml to go1.12 and run with GO111MODULE=on to make sure CI is actually testing with the versions listed here?

**Comment by andreykaipov** [comment]
Oh I was recently trying to get gengo to use Go modules too! 😄

To get the tests to pass (specifically `TestImportBuildPackage` from `parser/local_parse_test.go`), we have to add an empty `go.mod` to `vendor/fake/dep`:
```
module _

go 1.12
```

And reference it from the root `go.mod`:
```
module k8s.io/gengo

go 1.12

require (
        fake/dep v0.0.0
        ...
)

replace fake/dep v0.0.0 => ./vendor/fake/dep
```
In addition, because of an assumption the library took for importing packages (see [parser/parse.go#551](https://github.com/kubernetes/gengo/blob/master/parser/parse.go#L551)), we have to use `$(go list k8s.io/gengo/...)` instead of `k8s.io/gengo/...` directly for the second stage of the CI when verifying the examples (see [.travis.yml#L16](https://github.com/kubernetes/gengo/blob/master/.travis.yml#L16)).

The long-term solution would be to migrate from `go/build` to `golang.org/x/tools/go/packages` as recommended by the Go 1.11 release notes https://golang.org/doc/go1.11#gopackages. The way I understand it is by invoking `go list` ourselves, we're essentially doing what `go/packages` would do for us.

**Comment by lavalamp** [comment]
@andreykaipov Sure, that'd be great!

**Comment by estroz** [comment]
@andreykaipov are you working on this? If not I can take a stab at it.

**Comment by andreykaipov** [comment]
Hi @estroz - I'm not working on it. At the time of my comment I tried to do it but couldn't really wrap my head around it. :sweat_smile:

The only PR I have is the one above into this branch to get the CI working with Go modules, but that might have to change if `go/build` is replaced.

**Pull request closed without merging**
