### PR TITLE
update apimachinery package to match current state

### PR DESCRIPTION
**Pull request by deads2k**
https://github.com/kubernetes/kubernetes/pull/39475 moves the apimachinery to a logically separate repo under staging.  This updates the packages to match what will be coming.

@lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM after you update the generated files to fix the test.

**Comment by deads2k** [comment]
> LGTM after you update the generated files to fix the test.

Looks like we'll need that new repo before this passes.

**Comment by deads2k** [comment]
> Looks like we'll need that new repo before this passes.

considering the ordering, I suspect we'll prime the repo manually, then commit this pull, then update https://github.com/kubernetes/kubernetes/pull/39475 to bump gengo in the same pull that creates everything.

**Comment by lavalamp** [comment]
I thought it was just complaining because the checked-in file no longer
matches?

**Comment by deads2k** [comment]
> I thought it was just complaining because the checked-in file no longer
> matches?

It is, but the new file won't compile because k8s.io/apiserver doesn't exist yet

```
[deads@deads-dev-01 gengo]$ ./examples/deepcopy-gen/test.sh
Test logs are in /tmp/deepcopy.20545.yo0VrC
Testing wholepkg: PASS
test/wholepkg/deepcopy_generated.go:24:2: cannot find package "k8s.io/apimachinery/pkg/conversion" in any of:
	/home/deads/.gvm/gos/go1.7/src/k8s.io/apimachinery/pkg/conversion (from $GOROOT)
	/home/deads/workspaces/gengo/src/k8s.io/apimachinery/pkg/conversion (from $GOPATH)
FAIL

```

**Comment by lavalamp** [comment]
oh, I see, hm, I didn't think it compiled the generated files.

**Comment by deads2k** [comment]
Primed https://github.com/kubernetes/apimachinery closing and reopening it see if this kicks.

**Comment by deads2k** [comment]
we should get https://github.com/kubernetes/gengo/pull/31 first

**Comment by deads2k** [comment]
Something new now:
```
[deads@deads-dev-01 gengo]$ go get k8s.io/apimachinery/pkg/conversion
package k8s.io/apimachinery/pkg/conversion: unrecognized import path "k8s.io/apimachinery/pkg/conversion" (parse https://k8s.io/apimachinery/pkg/conversion?go-get=1: no go-import meta tags)


[deads@deads-dev-01 apimachinery]$ curl https://k8s.io/apimachinery/pkg/conversion?go-get=1
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>


[deads@deads-dev-01 apimachinery]$ curl https://k8s.io/kubernetes/pkg/conversion?go-get=1
<html><head>
  <meta name="go-import" content="k8s.io/kubernetes git https://github.com/kubernetes/kubernetes">
  <meta name="go-source" content="k8s.io/kubernetes     https://github.com/kubernetes/kubernetes https://github.com/kubernetes/kubernetes/tree/master{/dir} https://github.com/kubernetes/kubernetes/blob/master{/dir}/{file}#L{line}">
</head></html>
```

@lavalamp does something special need to happen on `https://k8s.io` for me to get the right response?

**Comment by thockin** [comment]
send a PR against https://github.com/kubernetes/k8s.io/blob/master/
k8s.io/configmap-www-golang.yaml, tag me.

**Comment by deads2k** [comment]
> send a PR against https://github.com/kubernetes/k8s.io/blob/master/
> k8s.io/configmap-www-golang.yaml, tag me.

Thanks, opened https://github.com/kubernetes/k8s.io/pull/41

**Comment by lavalamp** [comment]
Sorry! I meant to do that yesterday and forgot.

**Pull request merged**
