### PR TITLE
Channels deserve names, too

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
Travis failed.

**Comment by lavalamp** [comment]
Failure is due to making an illegal import, pre existing problem.

**Comment by thockin** [comment]
Does that mean we should merge this?  I'm LGTM, so go ahead if that is the right thing.

**Comment by lavalamp** [comment]
Yeah, we should get these imports fixed though.

**Pull request merged**
