### PR TITLE
fix deepcopy/sets generate of new year and remove YEAR field

### PR DESCRIPTION
**Pull request by fisherxu**
fix the new year of 2018 and remove YEAR field
 fix issue:[#24](https://github.com/kubernetes/gengo/issues/24)

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts pick to openshift fork please.

**Comment by sttts** [comment]
@deads2k we don't have boilerplate headers with YEARs.

**Comment by lavalamp** [comment]
This is a bit wrong-- *new* files should get the new year, but *old* files should not change.

Additionally, this appears to just modify the generated output instead of fixing the generator?

**Comment by sttts** [comment]
> This is a bit wrong-- new files should get the new year, but old files should not change.

I don't disagree. But is this a regression? I would prefer to get CI fixed first and do a proper fix in a follow-up. A quick look at the generator suggests that the code is pretty dumb just replacing the YEAR. We would have to write to a temporary file and do a fuzzy comparison.

**Comment by sttts** [comment]
Doesn't look like a regression. We had the same in 2017: https://github.com/kubernetes/gengo/issues/24

**Comment by thockin** [comment]
Agree - this sucks, but it's not on anyone's plate right now, and is not a trivial fix.

/lgtm

**Comment by thockin** [comment]
Need to also regenerate sets ?

**Comment by sttts** [comment]
Travis thinks so. @fisherxu can you update sets as well?

**Comment by fisherxu** [comment]
@sttts @thockin Have updated sets in another PR, xref: [92](https://github.com/kubernetes/gengo/pull/92) , and also add .gitignore for deepcopy-gen, PTAL. :)

**Comment by sttts** [comment]
@fisherxu can you merge both PR so that CI is happy? One alone won't be green ;)

**Comment by fisherxu** [comment]
@sttts  sure, have done :)

**Comment by sttts** [comment]
Lgtm. Maybe squash the two generation commits.

**Comment by fisherxu** [comment]
@sttts Have squashed :)
 Also add .gitignore for deepcopy and Makefile for set-gen. @thockin PTAL.
and will add test for default-gen later in another PR.

**Comment by fisherxu** [comment]
@thockin deepcopy and sets are all in this PR, can you help merge it? :)

**Comment by fisherxu** [comment]
@thockin @sttts Gentle ping, please review this PR and we should make CI for other PR green.

**Comment by fisherxu** [comment]
@thockin @lavalamp @sttts have removed the YEAR field in boilerplate, and regenerated, PTAL.

**Comment by fisherxu** [comment]
If we delete this line [#105](https://github.com/kubernetes/gengo/blob/master/args/args.go#L105), all the generated files in k/k will also be regenerated.

**Comment by sttts** [comment]
@fisherxu can you squash the first and last commit?

**Comment by fisherxu** [comment]
@sttts Sure, have done.

**Comment by sttts** [comment]
/lgtm

@thockin ptal.

**Comment by thockin** [comment]
Did we fix the kubernetes/kubernetes checker to not fail on the lack of a year?

**Comment by fisherxu** [comment]
@thockin This PR only affect generated files in gengo, kubernetes/kubernetes use another boilerplate in hack/boilerplate, and haven't fix it. Do we need to change generated files in kubernetes/kubernetes?

**Comment by sttts** [comment]
> Do we also need to change generated files in kubernetes/kubernetes?If we need fix that

Yes, basically the same as you have done here. Plus we have a CI checker for boilerplate in place that needs to be updated. That checker will have to check for date for non-generated files, but allow a missing date for generated files. So it's more complicated. But it is a follow-up of this PR.

@thockin can we merge this to make progress? The follow-up (revendoring) will have to fix the things in kube.

**Comment by sttts** [comment]
🎉

**Comment by fisherxu** [comment]
@thockin @sttts I find all generated files can be falled into two categories, one class of filenames contains generate and the other is under fixed folder like pkg/client/lister. Can we list all the folders and all the files contains generate, then do no YEAR field check. Other files do like before?

**Comment by fisherxu** [comment]
We can set generated_dirs like [skipped_dirs,](https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py#L132) then do no YEAR field check, look forward to hearing from your opinions :)

**Comment by sttts** [comment]
Yes, something in this direction. Haven't look at the boilerplate test script.

Note: there might be some files in those generated packages that are not generated (*_expansion.go). Not sure whether we actually use this feature in Kube though, maybe only in OpenShift. Just delete the folders, regenerate and compare which files are missing. Maybe that set is empty.

**Comment by fisherxu** [comment]
Have sent a PR to remove all YEAR field in k/k and also fix the checker, cc @thockin @lavalamp @sttts , ptal :)

**Comment by sttts** [comment]
@fisherxu I fear this conflicts with https://github.com/kubernetes/kubernetes/pull/57656

**Comment by fisherxu** [comment]
@sttts yes, I have seen at [kubernetes/kubernetes#59172](https://github.com/kubernetes/kubernetes/pull/59172) , we can wait kubernetes/kubernetes#57656 merge first.

**Comment by sttts** [comment]
@fisherxu working with @nikhita on it right now to get it in asap.

**Comment by fisherxu** [comment]
@sttts  No problem, I can help take a look for the failed CItests :)

**Comment by sttts** [comment]
@fisherxu fixing the path calculation right now. We don't want to hard-coded kube packages there.

**Comment by fisherxu** [comment]
@sttts Ok, talking with @nikhita now :)

**Pull request merged**
