### PR TITLE
typo

### PR DESCRIPTION
**Pull request by YunWang**
1. Typo
2. Handle return error when creates dir

### CODE REVIEW

**Comment by YunWang** [comment]
linuxfoundation

**Comment by YunWang** [comment]
I will handle `cla/linuxfoundation ` job late

**Comment by YunWang** [comment]
I signed it

**Comment by YunWang** [comment]
I signed it

**Comment by YunWang** [comment]
Who can tell me why cal/linuxfoundation doesn't pass and what's the problem?

**Comment by Jefftree** [comment]
hi @YunWang, please make sure your [commits](https://github.com/kubernetes/gengo/pull/189/commits) are attached to the same email used to sign the CLA.

**Comment by lavalamp** [comment]
Looks like you need to fix the email in the commit. https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Pull request closed without merging**
