### PR TITLE
Add output tests for deepcopy

### PR DESCRIPTION
**Pull request by thockin**
These are pretty basic tests but enough to look at for a start.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
```
FAIL: output files changed
make: *** [test] Error 1
make: Leaving directory `/home/travis/gopath/src/k8s.io/gengo/examples/deepcopy-gen'
The command "find . -name Makefile | xargs -n1 dirname | while read DIR; do make -C $DIR test; done" exited with 2.
```

**Comment by caesarxuchao** [comment]
Thanks, the tests look good, but travis needs fix.

**Comment by caesarxuchao** [comment]
Let's merge?

**Comment by thockin** [comment]
Merging.

**Pull request merged**
