### PR TITLE
import-boss: add inverse import rules

### PR DESCRIPTION
**Pull request by sttts**
Allow to restrict which packages Y may import a given package X via `InverseRules` in `X/.import-restrictions`:

```
//   "InverseRules": [{
//       "SelectorRegexp": "k8s[.]io",
//       "AllowedPrefixes": [
//         "k8s.io/same-repo",
//         "k8s.io/kubernetes/pkg/legacy"
//       ],
//       "ForbiddenPrefixes": [
//         "k8s.io/kubernetes/pkg/legacy/subpkg"
//       ]
//     },
//     {
//       "SelectorRegexp": "k8s[.]io",
//       "Transitive": true,
//       "AllowedPrefixes": [
//         "k8s.io/
//       ],
//       "ForbiddenPrefixes": [
//         "k8s.io/kubernetes/cmd/kubelet",
//         "k8s.io/kubernetes/cmd/kubectl"
//       ],
//   ]
// }
```

Example use-cases:
- k8s.io/apiserver/pkg/features feature gates should not leak into kubectl and kubelet (e.g. for https://github.com/kubernetes/kubernetes/pull/65558).
- k8s.io/kubernetes/pkg/master should only be imported transitively by cmd/kube-apiserver and cmd/hyperkube.
- k8s.io/apimachinery/pkg/private should only be imported directly by k8s.io/apimachinery, with the legacy exceptions a, b, c.

### CODE REVIEW

**Comment by lavalamp** [comment]
Sorry, I hadn't seen this. It'll be a bit but I think I should probably review it...

/assign

**Comment by sttts** [comment]
@lavalamp not sure where I was when doing this, might be incomplete. It's still something we want to have and @eloyekunle (current Google Summer of Code student of Kube) showed interest to continue this effort.

Also cc @dims

**Comment by sttts** [comment]
I had tests. So maybe it actually worked :)

**Comment by eloyekunle** [comment]
Yes, I'm interested in working on this, and I'll start looking into it next week.

**Comment by lavalamp** [comment]
Sounds good, let me know when it's ready for a look.

**Pull request closed without merging**
