### PR TITLE
Support parsing directives in comment of methods, structs, struct members and package doc

### PR DESCRIPTION
**Pull request by longit644**
This PR add support for parsing directives in comment of methods, structs, and struct members

### CODE REVIEW

**Comment by thockin** [comment]
Hi.  I am currently overhauling gnengo (https://github.com/kubernetes/gengo/pull/259) and looking at PRs.  

This PR doesn't explain WHY you need this, and keeping a fork of ast is not something we really want to do.

IF we were to consider this it would be on v2, and I don't think we want to at first glance.

**Comment by longit644** [comment]
Hi @thockin, 

Thank you for your response.

This PR adds parsing directive to support another new marker creation method for generator. It uses directive syntax `//k8s:...`, similar to how recent Go versions have transitioned from `// +build` to `//go:build`

If you believe this adds value to `gengo`, I would be happy to create another PR on `v2`.

**Comment by thockin** [comment]
Do those not get retained as comments?

I don't think we want to keep a fork of AST for this, especially after we move to packages.Load (PR pending)

**Comment by longit644** [comment]
No, directives are not retained within the comments. They are filtered out during the parsing process. 

As for keeping the fork of AST, I agree that may not be the most efficient approach. Instead, we could consider re-implementing the directive check or exploring alternative solutions.

**Comment by thockin** [comment]
I don't object to the goal, but I think it's trickier with `packages.Load` - try from my v2 PR as a base?

**Pull request closed without merging**
