### PR TITLE
Drop go.mod version to 1.20

### PR DESCRIPTION
**Pull request by thockin**
Also delete unusued testdata

### CODE REVIEW

**Comment by liggitt** [comment]
presubmit still doesn't exercise v2 stuff, did tests pass locally with this?

**Comment by thockin** [comment]
yes:

```
thockin-glaptop5 gengo e4602 master /v2$ git my
e4602e9  Drop go.mod version to 1.20

thockin-glaptop5 gengo e4602 master /v2$ go test ./...
?   	k8s.io/gengo/v2/examples/kilroy	[no test files]
?   	k8s.io/gengo/v2/examples/pointuh	[no test files]
?   	k8s.io/gengo/v2/examples/tracer	[no test files]
ok  	k8s.io/gengo/v2	(cached)
ok  	k8s.io/gengo/v2/generator	(cached)
ok  	k8s.io/gengo/v2/namer	(cached)
ok  	k8s.io/gengo/v2/parser	(cached)
ok  	k8s.io/gengo/v2/types	(cached)

```

**Comment by liggitt** [comment]
```
$ make test
go test -race ./...
?   	k8s.io/gengo/args	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/aliases	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/builtins	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/interfaces	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/maps	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/otherpkg	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/pointer	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/slices	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/structs	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/generators	[no test files]
ok  	k8s.io/gengo/examples/deepcopy-gen/generators	1.263s
?   	k8s.io/gengo/examples/import-boss/tests/inverse/a	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/b	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/c	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/d	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/nonprod	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/public	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/private	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/quarantine	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/a	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/b	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/c	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested/nested/inherit	[no test files]
?   	k8s.io/gengo/examples/set-gen	[no test files]
?   	k8s.io/gengo/examples/set-gen/generators	[no test files]
?   	k8s.io/gengo/examples/set-gen/sets/types	[no test files]
ok  	k8s.io/gengo/examples/deepcopy-gen/output_tests	3.490s
ok  	k8s.io/gengo/examples/deepcopy-gen/output_tests/wholepkg	1.324s
ok  	k8s.io/gengo/examples/import-boss	7.838s
ok  	k8s.io/gengo/examples/import-boss/generators	1.288s
ok  	k8s.io/gengo/examples/import-boss/tests/inverse/lib	1.181s [no tests to run]
ok  	k8s.io/gengo/examples/set-gen/sets	1.133s
ok  	k8s.io/gengo/generator	1.229s
ok  	k8s.io/gengo/namer	1.327s
ok  	k8s.io/gengo/parser	1.388s
ok  	k8s.io/gengo/types	1.360s
./hack/verify-examples.sh
Removing generated code
Generating example output...
W0227 19:56:53.473206   14198 parse.go:247] Ignoring directory k8s.io/gengo/examples/defaulter-gen/output_tests: No files for pkg "k8s.io/gengo/examples/defaulter-gen/output_tests"
Running tests...
?   	k8s.io/gengo/examples/deepcopy-gen	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/aliases	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/builtins	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/interfaces	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/maps	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/otherpkg	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/pointer	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/structs	[no test files]
?   	k8s.io/gengo/examples/deepcopy-gen/output_tests/slices	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/generators	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/a	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/b	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/c	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/d	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/nonprod	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/private	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/public	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/inverse/lib/quarantine	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/a	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/b	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/c	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested/nested	[no test files]
?   	k8s.io/gengo/examples/import-boss/tests/rules/nested/nested/nested/inherit	[no test files]
?   	k8s.io/gengo/examples/set-gen	[no test files]
?   	k8s.io/gengo/examples/set-gen/generators	[no test files]
?   	k8s.io/gengo/examples/set-gen/sets/types	[no test files]
ok  	k8s.io/gengo/examples/deepcopy-gen/generators	0.445s
ok  	k8s.io/gengo/examples/deepcopy-gen/output_tests	0.557s
ok  	k8s.io/gengo/examples/deepcopy-gen/output_tests/wholepkg	0.383s
ok  	k8s.io/gengo/examples/import-boss	6.323s
ok  	k8s.io/gengo/examples/import-boss/generators	0.606s
ok  	k8s.io/gengo/examples/import-boss/tests/inverse/lib	0.655s [no tests to run]
ok  	k8s.io/gengo/examples/set-gen/sets	0.613s
?   	k8s.io/gengo/examples/defaulter-gen/output_tests	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/empty	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/marker/external	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/marker/external/external	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/marker/external2	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/marker/external3	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/pointer	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/slices	[no test files]
?   	k8s.io/gengo/examples/defaulter-gen/output_tests/wholepkg	[no test files]
ok  	k8s.io/gengo/examples/defaulter-gen/output_tests/marker	0.377s
go -C v2 test -race ./...
?   	k8s.io/gengo/v2/examples/kilroy	[no test files]
?   	k8s.io/gengo/v2/examples/pointuh	[no test files]
?   	k8s.io/gengo/v2/examples/tracer	[no test files]
ok  	k8s.io/gengo/v2	1.156s
ok  	k8s.io/gengo/v2/generator	1.326s
ok  	k8s.io/gengo/v2/namer	1.476s
ok  	k8s.io/gengo/v2/parser	1.864s
ok  	k8s.io/gengo/v2/types	1.559s
(cd v2 && ./hack/verify-examples.sh)
Running tests...
?   	k8s.io/gengo/v2/examples/kilroy	[no test files]
?   	k8s.io/gengo/v2/examples/pointuh	[no test files]
?   	k8s.io/gengo/v2/examples/tracer	[no test files]
```

/lgtm
/approve

**Comment by shashankram** [comment]
> Drop go.mod version to 1.20

@thockin what was the reason to downgrade the version?

**Comment by thockin** [comment]
go.mod versions are viral, and any consumer of gengo was forced to use Go 1.21 when there was no real reason.  Gengo doesn't actually NEED newer versions.

**Pull request merged**
