### PR TITLE
deepcopy: fix lint issues

### PR DESCRIPTION
**Pull request by sttts**
- receiver name x should be consistent with previous receiver name in for Requirement
- comment on exported function GetGeneratedDeepCopyFuncs should be of the form "GetGeneratedDeepCopyFuncs ..."

### CODE REVIEW

**Comment by sttts** [comment]
/assign @smarterclayton 

This is a follow-up for static deepcopy.

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
You need to regenerate the output tests, though.  `make`.

**Comment by sttts** [comment]
@thockin updated.

**Comment by sttts** [comment]
Rebased

**Pull request merged**
