### PR TITLE
Add SnippetWriter.Dup(), fix bug in Args.With()

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
https://github.com/kubernetes/test-infra/pull/33301

**Comment by jpbetz** [comment]
/lgtm

This looks right to me.

**Comment by jpbetz** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/gengo/272/pull-gengo-verify/1823078595799552000/build-log.txt looks like a problem with pre-submit unrelated to this PR.

**Comment by jpbetz** [comment]
/retest
`make - verify` passes locally

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes/test-infra/pull/33302 to fix the verify failure. This can be retested once that merges.

**Comment by jpbetz** [comment]
Oops, I didn't see https://github.com/kubernetes/gengo/pull/272#issuecomment-2284770729 comments..

**Pull request merged**
