### PR TITLE
Fix some typos in example

### PR DESCRIPTION
**Pull request by huangqg**
Fix some typos in example files:

1. examples/deepcopy-gen/generators/deepcopy.go
2. examples/deepcopy-gen/main.go

### CODE REVIEW

**Comment by nikhita** [comment]
@huangqg Looks good. :) Can you squash the commits to a single commit? Thanks!

**Comment by huangqg** [comment]
> @huangqg Looks good. :) Can you squash the commits to a single commit? Thanks!

Done!

**Comment by nikhita** [comment]
@huangqg One more quick thing, can you rename the commit message to say something like `examples: fix typo in comments`?

This way if someone looks through `git log` or `git blame`, it's easy for them to understand what the commit changed. :)

**Comment by sttts** [comment]
Maybe the test cases must be regenerated? Travis is unhappy.

**Pull request closed without merging**
