### PR TITLE
Fix golint errors in generated files by `deepcopy-gen`.

### PR DESCRIPTION
**Pull request by tossmilestone**
Fix golint errors in generated files by `deepcopy-gen`.

See #96

### CODE REVIEW

**Comment by sttts** [comment]
Looks good in general. Please update the output tests to make travis happy.

**Comment by tossmilestone** [comment]
@sttts updated, PTAL.

**Comment by sttts** [comment]
/lgtm

For the record: I wanted to comment "just do `return in.DeepCopy()`". But that's not correct as it return a non-nil interface with a nil pointer inside, instead of a nil-interface. A comment wouldn't be wrong maybe in the generator code.

**Pull request merged**
