### PR TITLE
Only add to tracker if it's non-local

### PR DESCRIPTION
**Pull request by lavalamp**
Import tracker was supposed to handle this case, but it seems local package was never plumbed through. Maybe lost in the protobuf addition?

### CODE REVIEW

**Comment by lavalamp** [comment]
@smarterclayton I vaguely recall you saying something about this.

**Comment by smarterclayton** [comment]
Wow that's so long ago I don't even know.  I think I ended up adding this all over the place in protobuf though.

**Comment by lavalamp** [comment]
Yeah, the whole point was that the naming system should be doing this for you. But somehow the NewImportTracker method in the generator package doesn't let you specify your local package. Really that's where it should be fixed, but this is OK too.

**Comment by thockin** [comment]
Is this worth re-considering?

**Comment by lavalamp** [comment]
Yes, this should be fixed. I almost want to fork this whole package and fix everything :(

**Comment by thockin** [comment]
rename it to Vampire because it has no reflection :)

**Pull request closed without merging**
