### PR TITLE
Defaults: Don't look at JSON omitempty

### PR DESCRIPTION
**Pull request by thockin**
Looking at JSON is weird, and the intersection of non-omitempty and having a default seems valid.

It seems like this was asserting that "if you have an out-of-bounds zero-value, you must set omitempty", but I don't buy that and looking at JSON tags is just weird.

### CODE REVIEW

**Comment by thockin** [comment]
hold for discussion

**Review by alexzielenski — APPROVED** [review]
/lgtm

agreed I cant think of a reason why `omitempty` should be forced into a default of zero. And for the purposes of defaulter-gen it makes sense to ignore zero-valued defaults (in constrast to OpenAPI-gen)

**Comment by apelisse** [comment]
So we can continue discussing it before merging.
/hold

**Comment by apelisse** [comment]
cc @liggitt

**Comment by apelisse** [comment]
> agreed I cant think of a reason why omitempty should be forced into a default of zero.

Actually I read "why non-omitempty" should be forced into a default of zero. omitempty shouldn't have to.

**Comment by apelisse** [comment]
> I think that is why putting a default on a non-omitempty field is weird, because clients are unaware 0 will be defaulted.

Yes, I think that's an important point, and also something they can not avoid when using typed clients.

**Comment by apelisse** [comment]
> In [KEP-4153](https://github.com/alexzielenski/enhancements/blob/declarative-validation/keps/sig-api-machinery/4153-declarative-validation/README.md#zero-valued-primitive-fields) we discuss Zero-valued primitive fields and problems they cause for unstructured validation. The proposed solution there is to annotate x-kubernetes-strip-zero: true to non-pointer primitive fields to inform clients that the empty value is treated as unset. I think that would also clear the ambiguity the code generator restriction is trying to prevent here.

Yeah, the whole point of the exercise we've done in the defaulting KEP was to avoid introducing a new non-standard extension. Didn't we argue that we could just apply the defaults before running the CEL expression to have consistency between built-ins and CRDs?

**Comment by thockin** [comment]
> all typed-clients are sending invalid values over the wire

Only if they send JSON.  And even so, who cares?  Most (all) of these fields ARE `omitempty` in k/k so this is a no-op except that it eliminates a weird corner case and layering violation.

Why shouldn't we also look at proto tags?  Or Yaml tags?

> I think that is why putting a default on a non-omitempty field is weird, because clients are unaware 0 will be defaulted.

In hindsight, yes and we have (mostly) stopped doing that :)

**Comment by apelisse** [comment]
> Why shouldn't we also look at proto tags? Or Yaml tags?

Yes, OK, that's weird ;-)

**Comment by thockin** [comment]
That's my point.  Defaulting code shouldn't be looking at JSON tags.

**Comment by thockin** [comment]
I just realized this is still open - @alexzielenski or @jpbetz - opinions?

**Comment by jpbetz** [comment]
It took me a while to figure out what was happening before and, yeah, I'm fully behind this approach.

Code looks good, I couldn't find anything to pick at.

/lgtm
/approve

Leaving the hold in your hands @thockin

**Comment by thockin** [comment]
I verified that this does not change any generated code in k/k

**Pull request merged**
